// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiarxphbkbxhkttrwlqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYXJ4cGhia2J4aGt0dHJ3bHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjQyNTIsImV4cCI6MjA2MDU0MDI1Mn0.J0BipfGVh3x9tR0bkI05TEy3t9cuwmDQo17wQL4ZaFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);